---
datacenter:
  children:
    routers:
      hosts:
        R5-1:
          ansible_host: 10.215.28.193
        R5-2:
          ansible_host: 10.215.28.192

  vars:
    ansible_become_password: vnpro#321
    ansible_user: vnpro
    ansible_password: vnpro#123
    ansible_connection: network_cli
    ansible_become: "yes"
    ansible_become_method: "enable"
    ansible_network_os: ios
